### ISSUE TITLE
Got this issue 

### ISSUE THREAD

**Issue by Jackblack007** [namra004/How-to-use-Parallels-Desktop-for-free#2]
![Screen Shot 2020-01-01 at 12 30 30 AM](https://user-images.githubusercontent.com/47188058/196826624-8b88cd99-6432-43aa-a1d7-0063c5548157.png)

**Comment by namra004** [comment]
You’ve rotten you macs name not your users one, change it to your user name or use shell script that I wrote.

**Comment by namra004** [comment]
Written*
