### ISSUE TITLE
What is. FOLDER_WHERE_DOC_WAS_PUT ?

### ISSUE THREAD

**Issue by eromoe** [namra004/How-to-use-Parallels-Desktop-for-free#3]
1. cd to home
2. cd to download
3. change time
4. open paralells
5. cd to home
6. cd to download 
7. change time back

I don't understand why I need  : 
1. cd to home
2. cd to download

At least this method doesn't work for me

**Comment by namra004** [comment]
you cd there to get the password of Mac from txt document

**Comment by eromoe** [comment]
so `cd`  is useless ,  you only need give the absolute path
